name: Generate CodeMeta

on: push

jobs:
  generate-codemeta:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Groovy
        run: sudo apt install groovy
      
      - name: Run CodeMeta generation script
        run: bash generate-all.sh
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Automated generation of CodeMeta files using GitHub Actions